import { GoogleGenAI, Modality } from "@google/genai";
import { AspectRatio } from '../types';

if (!process.env.API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

// Helper function to extract base64 data and mimeType from a data URL
const parseDataUrl = (dataUrl: string): { mimeType: string; data: string } => {
  const parts = dataUrl.split(',');
  const mimeType = parts[0].match(/:(.*?);/)?.[1];
  if (!mimeType || !parts[1]) {
    throw new Error('Invalid data URL format');
  }
  return { mimeType, data: parts[1] };
};


export const generateMockupImage = async (
  productName: string,
  aspectRatio: AspectRatio['value'],
  uploadedImage: string | null,
  customPrompt?: string
): Promise<string> => {
  try {
    // Logic for when a reference image is provided
    if (uploadedImage) {
      const { mimeType, data: base64ImageData } = parseDataUrl(uploadedImage);

      const imagePart = {
        inlineData: {
          mimeType,
          data: base64ImageData,
        },
      };

      const textPrompt = `Based on the provided image, create a professional product mockup of a "${productName}". The mockup should be photorealistic, high-detail, 8K, and suitable for commercial use. Place the product on a clean, minimalist studio background with deep blue and purple tones. ${customPrompt || ''}`;
      
      const textPart = { text: textPrompt };

      const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: { parts: [imagePart, textPart] },
        config: {
          responseModalities: [Modality.IMAGE],
        },
      });
      
      for (const part of response.candidates[0].content.parts) {
        if (part.inlineData) {
          const base64ImageBytes = part.inlineData.data;
          const imageMimeType = part.inlineData.mimeType;
          return `data:${imageMimeType};base64,${base64ImageBytes}`;
        }
      }
      throw new Error("No image was generated by the API from the reference image.");

    } else {
      // Original logic for generating from scratch
      const fullPrompt = `Professional product photography of a ${productName}. Clean, minimalist studio background in deep blue and purple tones. Photorealistic, 8K, high detail, commercial mockup. ${customPrompt || ''}`;

      const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: fullPrompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png',
          aspectRatio: aspectRatio,
        },
      });

      if (response.generatedImages && response.generatedImages.length > 0) {
        const base64ImageBytes = response.generatedImages[0].image.imageBytes;
        return `data:image/png;base64,${base64ImageBytes}`;
      } else {
        throw new Error("No image was generated by the API.");
      }
    }
  } catch (error) {
    console.error("Error generating image with Gemini:", error);
     if (error instanceof Error && error.message.includes('Invalid data URL format')) {
      throw new Error("The uploaded image file is corrupted or in an unsupported format. Please try another image.");
    }
    throw new Error("Failed to generate mockup. Please try again.");
  }
};